version: '3.8'

services:
  mct-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - elasticsearch
    restart: always
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
      - redis-insight
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    restart: always
  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 2GB