version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
  elasticsearch:
    image: elasticsearch:8.7.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      resources:
        limits:
          memory: 2GB