version: '3.8'

services:
  mct-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mct-app
    ports:
      - 443:443
    depends_on:
      - elasticsearch
      - redis
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always


  elasticsearch:
    image: elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 2GB

