version: '3.8'

services:
  mct-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mct-app
    ports:
      - 443:443
    depends_on:
      - db
      - elasticsearch
      - redis
    restart: always
    volumes:
      - app_files:/app/mct_app/files
      - logs:/app/logs
      - migrations:/app/migrations
      - banned_ip:/app/banned_ip

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery
    environment:
      FLASK_APP: manage
    depends_on:
      - db
      - redis
      - elasticsearch
    restart: always

  db:
    image: postgres:16.3
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mct_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always


  pg_admin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: always

  elasticsearch:
    image: elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 2GB
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    

volumes:
  postgres_data:
  app_files:
  logs:
  pgadmin_data:
  migrations:
  banned_ip:
  esdata: