[tool.poetry]
name = "metacognitive site"
version = "1.0"
description = "A website about metacognitive therapy"
authors = ["Ivan Zaycev"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
