"""empty message

Revision ID: 4cbafa17133c
Revises: 
Create Date: 2024-05-06 14:18:22.629624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbafa17133c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('last_activity',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('last_activity',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)

    # ### end Alembic commands ###
