"""empty message

Revision ID: 95305370a8c5
Revises: 
Create Date: 2024-07-22 21:39:43.673940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95305370a8c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banned_ip', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banned_ips'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned_ips')
    # ### end Alembic commands ###
