"""empty message

Revision ID: f3b324b81ebd
Revises: 
Create Date: 2024-06-12 15:59:25.291932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b324b81ebd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Enum('HAPPY', 'IRRITATED', 'RELAXED', 'CONCERNED', 'RESTLESS', 'DISAPPOINTED', name='mood'), nullable=False))
        batch_op.drop_column('mood')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(length=12), nullable=False))
        batch_op.drop_column('value')

    # ### end Alembic commands ###
